Sync Markdown checks with "template"
We have assembled a collection of reusable project assets:
https://github.com/arduino/tooling-project-assets
These will be used in the repositories of all Arduino tooling projects.

Some improvements and standardizations have been made in the upstream "template" assets for checking the general quality
of Mardown files. Those are introduced to this repository here.

Notable:

- Make link check task Windows compatible
- Use markdownlint-cli to check for common problems and style.
- Bring repository into compliance with the standard Markdown style for Arduino tooling projects

NOTE: the `docs:check-links` task has been renamed to `markdown:check-links` for consistency with the standard
"template" task name.

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -46,20 +46,6 @@ tasks:
     cmds:
       - npx {{ .PRETTIER }} --check "**/*.md"
 
-  docs:check-links:
-    desc: Verifies there are no dead links in documentation
-    deps:
-      - task: docs:generate
-    cmds:
-      - |
-        npx -p markdown-link-check -c '
-        STATUS=0
-        for file in $(find -name "*.md"); do
-          markdown-link-check -c markdown-link-check-config.json -q "$file"
-          STATUS=$(( $STATUS + $? ))
-        done
-        exit $STATUS'
-
   docs:format:
     desc: Automatically formats documentation
     cmds:
@@ -72,6 +58,61 @@ tasks:
       - poetry:install-deps
     cmds:
       - poetry run mkdocs build -s
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
+  markdown:check-links:
+    desc: Check for broken links
+    deps:
+      - task: docs:generate
+    cmds:
+      - |
+        if [[ "{{.OS}}" == "Windows_NT" ]]; then
+          # npx --call uses the native shell, which makes it too difficult to use npx for this application on Windows,
+          # so the Windows user is required to have markdown-link-check installed and in PATH.
+          if ! which markdown-link-check &>/dev/null; then
+            echo "markdown-link-check not found or not in PATH. Please install: https://github.com/tcort/markdown-link-check#readme"
+            exit 1
+          fi
+          # Default behavior of the task on Windows is to exit the task when the first broken link causes a non-zero
+          # exit status, but it's better to check all links before exiting.
+          set +o errexit
+          STATUS=0
+          # Using -regex instead of -name to avoid Task's behavior of globbing even when quoted on Windows
+          # The odd method for escaping . in the regex is required for windows compatibility because mvdan.cc/sh gives
+          # \ characters special treatment on Windows in an attempt to support them as path separators.
+          for file in $(find . -regex ".*[.]md"); do
+            markdown-link-check \
+              --quiet \
+              --config "./.markdown-link-check.json" \
+              "$file"
+            STATUS=$(( $STATUS + $? ))
+          done
+          exit $STATUS
+        else
+          npx --package=markdown-link-check --call='
+            STATUS=0
+            for file in $(find . -regex ".*[.]md"); do
+              markdown-link-check \
+                --quiet \
+                --config "./.markdown-link-check.json" \
+                "$file"
+              STATUS=$(( $STATUS + $? ))
+            done
+            exit $STATUS
+          '
+        fi
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
+  markdown:fix:
+    desc: Automatically correct linting violations in Markdown files where possible
+    cmds:
+      - npx markdownlint-cli --fix "**/*.md"
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
+  markdown:lint:
+    desc: Check for problems in Markdown files
+    cmds:
+      - npx markdownlint-cli "**/*.md"
 
   build:
     desc: Build the project
@@ -105,6 +146,8 @@ tasks:
       - task: docs:check
       - task: config:check
       - task: general:check-formatting
+      - task: markdown:check-links
+      - task: markdown:lint
       - task: python:check
 
   config:check:
